node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
      
      console.log('============= PRPRPRPRPR ===============');
        console.log(dockerhub);
      
     docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
        
        
        console.log('=========================================');
       def app = docker.build("patelpareshr/nodejs-demo:${commit_id}", '.').push()
        console.log(app);
        console.log('=======================Above is APP value =============');
     }
   }
}
